// This is the main game variable. Stores a majority of one's individual game information and settings//

let game = {
	general: {
		version: 0.0,
	},
	current: {
		collecting: null,
		resources: {
			herb: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageTotal: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				active: {
					activeBase: 1,
					activeTotal: 1,
					activeUpgrades: 0,
					activeBaseCost: 100,
					activeCostIncrement: 1.5,
					activeBaseBonus: 1,
				},
				golemPerSec: 0,
				totalPerSec: 0,
			},
			mythril: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageTotal: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				active: {
					activeBase: 1,
					activeTotal: 1,
					activeUpgrades: 0,
					activeBaseCost: 100,
					activeCostIncrement: 1.5,
					activeBaseBonus: 1,
				},
				golemPerSec: 0,
				totalPerSec: 0,
			},
			yew: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageTotal: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				active: {
					activeBase: 1,
					activeTotal: 1,
					activeUpgrades: 0,
					activeBaseCost: 100,
					activeCostIncrement: 1.5,
					activeBaseBonus: 1,
				},
				golemPerSec: 0,
				totalPerSec: 0,
			},
			crystal: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageTotal: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				active: {
					activeBase: 1,
					activeTotal: 1,
					activeUpgrades: 0,
					activeBaseCost: 100,
					activeCostIncrement: 1.5,
					activeBaseBonus: 1,
				},
				golemPerSec: 0,
				totalPerSec: 0,
			},
			arcana: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageTotal: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				active: {
					activeBase: 1,
					activeTotal: 1,
					activeUpgrades: 0,
					activeBaseCost: 100,
					activeCostIncrement: 1.5,
					activeBaseBonus: 1,
				},
				golems: {
					golemsBase: 1,
					golemsTotal: 0,
				},
				golemPerSec: 0,
				totalPerSec: 0,
			},
			golems: {
				assignmentType: 'assign',
				inactive: 0,
				active: 0,
				total: 0,
				storage: {
					storageBase: 10,
					storageTotal: 10,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 5,
				},
				types: {
					herb: 0,
					mythril: 0,
					yew: 0,
					crystal: 0,
					arcana: 0,
				},
				cost: {
					baseCost: 100,
					totalCost: 100,
				},
			},
		},
		combat: {
			world: 0,
			floor: 0,
			room: 0,
			player: {
				healthMax: 100,
				healthCurrent: 100,
				attack: 1,
				defense: 0,
			},
			enemy: {
				healthMax: 100,
				healthCurrent: 100,
				attack: 1,
				defense: 0,
			},
		},
	},
	best: {},
};
