// This is the main game variable. Stores a majority of one's individual game information and settings//

let game = {
	general: {
		version: 0.0,
	},
	current: {
		collecting: null,
		resources: {
			herb: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageMax: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				activePerSec: 1,
				activeUpgrades: 0,
				golemPerSec: 0,
				totalPerSec: 0,
			},
			mythril: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageMax: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				activePerSec: 1,
				activeUpgrades: 0,
				golemPerSec: 0,
				totalPerSec: 0,
			},
			yew: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageMax: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				activePerSec: 1,
				activeUpgrades: 0,
				golemPerSec: 0,
				totalPerSec: 0,
			},
			crystal: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageMax: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				activePerSec: 1,
				activeUpgrades: 0,
				golemPerSec: 0,
				totalPerSec: 0,
			},
			arcana: {
				current: 0,
				total: 0,
				storage: {
					storageBase: 250,
					storageMax: 250,
					storageUpgrades: 0,
					storageBaseCost: 50,
					storageCostIncrement: 2,
					storageBaseBonus: 2,
				},
				activePerSec: 1,
				activeUpgrades: 0,
				golemPerSec: 0,
				totalPerSec: 0,
			},
		},
		golems: {
			inactive: 0,
			active: 0,
			total: 0,
			storageMax: 10,
			storageUpgrades: 0,
		},
	},
	best: {},
};
